# Generated by Django 6.0.4 on 2026-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weatherstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='station_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
