# Generated by Django 6.0.4 on 2026-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weatherstation_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherstation',
            old_name='humidity',
            new_name='humidity_pct',
        ),
        migrations.RenameField(
            model_name='weatherstation',
            old_name='temperature',
            new_name='temperature_c',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='pressure',
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='battery_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='measured_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='pressure_hpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='signal_rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
