# Generated by Django 6.0.4 on 2026-04-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_humidity_weatherstation_humidity_pct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherstation',
            old_name='temperature_c',
            new_name='temperature',
        ),
    ]
