# Generated by Django 6.0.4 on 2026-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_temperature_c_weatherstation_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='perspiration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
