# Generated by Django 6.0.4 on 2026-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_weatherstation_perspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='batch_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
